services:
 menufy-backoffice:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "${PORT:-5173}:${PORT:-5173}"
  environment:
   - VITE_BACKEND_URL=http://host.docker.internal:5000/api
   - VITE_FACE_BACKEND_URL=http://host.docker.internal:5001
   - VITE_FLASK_BACKEND_URL=http://host.docker.internal:5001
  env_file:
   - .env
  restart: unless-stopped
